### ISSUE TITLE
Config files export successfully, yet writing them doesn't work (except for --hard_reset flag)

### ISSUE THREAD

**Issue by casanovalx** [so1der/m601#4]
Hello. Had such a dillema. I decided to test the software and set it up, yet met an unexpected turn of events. The software can pull the current config from the mouse, yet can't write it to it, whatever you do, - only --hard_reset flag works. Is there any workaround with it?

Specs, just in case:

Laptop: Lenovo ideapad Y700-15ISK
Processor: Intel Core i5-6300HQ
GPUs: Intel HD 530 + Nvidia GTX 960M
RAM: 2x8 GB
Hub that connects the mouse: some Novodesk I bought from ozon.by for 'round 20 BYN
OS: openSUSE Tumbleweed

**Comment by so1der** [comment]
Hello there! That's interesting.
Does any error appear, or something?
Does the mode change command not work as well?
```
python cli.py -m 1  
```
That's interesting because, to pull the config from the mouse, this software needs to send a specific command to it. So it can communicate with the mouse, but still, it can't send the new config. Hmm.

**Comment by casanovalx** [comment]
> Hello there! That's interesting. Does any error appear, or something? Does the mode change command not work as well?
> 
> ```
> python cli.py -m 1  
> ```
> 
> That's interesting because, to pull the config from the mouse, this software needs to send a specific command to it. So it can communicate with the mouse, but still, it can't send the new config. Hmm.

Just checked. No errors. Neither there are in attempt to load the modified config. The software thinks that the config is uploaded, yet it's not

**Comment by so1der** [comment]
Hmm, are you familiar with Wireshark? It can "sniff" USB packets, and it would be really helpful to look at them. For example, we could compare your packets with mine.
Also, do you have the `M601-RGB` version of the mouse, or just the `M601`? Because when I created this repository, I simply didn't know about the existence of the regular M601 version :D 
That's why the repository name may be misleading.

**Comment by casanovalx** [comment]
> Hmm, are you familiar with Wireshark? It can "sniff" USB packets, and it would be really helpful to look at them. For example, we could compare your packets with mine. Also, do you have the `M601-RGB` version of the mouse, or just the `M601`? Because when I created this repository, I simply didn't know about the existence of the regular M601 version :D That's why the repository name may be misleading.

First, not really, yet can easily install it. Second, I definitely have the M601-RGB (they differ with both code and name: the M601 is just Redragon Centrophorus, and the M601 RGB is Redragon Centrophorus 2)

**Comment by so1der** [comment]
Great! Then we can use Wireshark to check whether the packets are being formed correctly and whether the mouse reacts to them at all.

For example, I just tried switching the mouse mode to the first mode. You can unpack and open this file in Wireshark. I can see that the packet was formed correctly (the control bytes are visible – `05 02 01`), and the mouse responded to it by sending some kind of package.

You can try capturing an attempt to change the mode and an attempt to send the config using Wireshark (preferably as separate files). [This article](https://wiki.wireshark.org/CaptureSetup/USB) might help.

One more thing – since Wireshark will capture ALL packets of specific USB port, it's best to connect the mouse directly rather than through a hub during testing. Also, flip it upside down so that the sensor doesn’t work, and use laptop's touchpad,  because every mouse movement generates thousands of packets that Wireshark will also capture, making it extremely difficult to find required packages.

I'll try my best to understand something from packages that You will provide. 

[change_mode.tar.gz](https://github.com/user-attachments/files/18789707/change_mode.tar.gz)

**Comment by casanovalx** [comment]
> Great! Then we can use Wireshark to check whether the packets are being formed correctly and whether the mouse reacts to them at all.
> 
> For example, I just tried switching the mouse mode to the first mode. You can unpack and open this file in Wireshark. I can see that the packet was formed correctly (the control bytes are visible – `05 02 01`), and the mouse responded to it by sending some kind of package.
> 
> You can try capturing an attempt to change the mode and an attempt to send the config using Wireshark (preferably as separate files). [This article](https://wiki.wireshark.org/CaptureSetup/USB) might help.
> 
> One more thing – since Wireshark will capture ALL packets of specific USB port, it's best to connect the mouse directly rather than through a hub during testing. Also, flip it upside down so that the sensor doesn’t work, and use laptop's touchpad, because every mouse movement generates thousands of packets that Wireshark will also capture, making it extremely difficult to find required packages.
> 
> I'll try my best to understand something from packages that You will provide.
> 
> [change_mode.tar.gz](https://github.com/user-attachments/files/18789707/change_mode.tar.gz)

Okay... Either I'm doing something wrong, or I don't know. I honestly didn't understand the article, and there are 3 usbmon mount points - usbmon0, usbmon1 and usbmon2 (the last one is from the laptop's webcam, I guess), and I just can't detect the exactly needed thing as it all moves TOO fast xD

**Comment by casanovalx** [comment]
I'll tell you more: in neither of the mount points, I didn't caught any URB_CONTROL signals, which's weird by itself

**Comment by so1der** [comment]
No, if you were able to see the USB packets, then the article has already done its job :)

Regarding usbmon0, usbmon1, usbmon2 – if I'm not mistaken, these are the USB ports. However, it seems that this could also be a USB hub inside the laptop if the laptop has more than three USB ports. Or some other devices connected to the internal USB bus, yes.

You can identify the correct usbmon interface by opening it and moving the mouse back and forth – a whole bunch of `USB_INTERRUPT` packets will be generated. That’s the one you need. If other packets appear even when the mouse is inactive, then that’s strange.

When I move my mouse, it generates `USB_INTERRUPT` packets. `USB_CONTROL` appears only when I try to change the mouse mode (or trying to upload config, if I recall correctly)

**Comment by casanovalx** [comment]
> No, if you were able to see the USB packets, then the article has already done its job :)
> 
> Regarding usbmon0, usbmon1, usbmon2 – if I'm not mistaken, these are the USB ports. However, it seems that this could also be a USB hub inside the laptop if the laptop has more than three USB ports. Or some other devices connected to the internal USB bus, yes.
> 
> You can identify the correct usbmon interface by opening it and moving the mouse back and forth – a whole bunch of `USB_INTERRUPT` packets will be generated. That’s the one you need. If other packets appear even when the mouse is inactive, then that’s strange.
> 
> When I move my mouse, it generates `USB_INTERRUPT` packets. `USB_CONTROL` appears only when I try to change the mouse mode (or trying to upload config, if I recall correctly)

Fun thing is, that the usbmon2 is inactive, and there's one DEVICE request from the webcam (to be exact, from it's depth sensor), and after 68th package, it halts. Yet the other two ALWAYS send packages from the mouse, which's weird (I even disconnected all the cables and hubs except for my mouse (yet I guess that the right two USBs are connected in one hub, yet I'm not sure), so it's weird

**Comment by casanovalx** [comment]
Okay, hol' up! I got it, I guess. The URB_CONTROL flag appeared ONLY when I used the CLI tool, not via the button. On the upload (not switching mode), it gives from 00 02 01 to 83 02 01, I'll try with mode switch now

**Comment by casanovalx** [comment]
Uh-huh... yet on the mode switch, it simply gives 00 02 01, not the 05 02 01, which already is weird...
It's on lines 739 and 740:

[urb_control.tar.gz](https://github.com/user-attachments/files/18796819/urb_control.tar.gz)

**Comment by so1der** [comment]
Hmm, but I can see the correct data on line 739 – 05 02 02, switching to mode 2

![Image](https://github.com/user-attachments/assets/1ecee9a9-121f-4906-9879-935fa6360f80)

Yet, on line 751, there is another control packet that seems weird

![Image](https://github.com/user-attachments/assets/d4c75282-d0c5-4486-871e-d796c7014208)

So, the mouse didn’t react to the packet on line 739 at all?

Because no matter what mode it was in before, when I try to change the mode (even from the 1 mode to the 1 mode), the mouse still reacts by displaying the mode color. (It can be changed in the software, but by default, it seems to be blue and red.)

**Comment by casanovalx** [comment]
...Huh? Now that's somethin' definitely weird... When I press the button, it changes color to red and blue indeed... yet just re-checked, it just refreshes the lighting when the python3 cli.py -m 1/2 is written, aka "resets" the lighting to the start point, without changing the mode

**Comment by so1der** [comment]
That's really interesting..
Well, as far as I can tell, there are no issues with the packets, so the program is functioning as it should, and the system isn't interfering either. Yet, the mouse still doesn't react to the packets or reacts strangely...

Could they have somehow changed the protocol? But then it would be strange that the program can still fetch the settings from the mouse. 

Have you ever tried to use a program from the manufacturer that is for Windows, or is this your first attempt at setting up a mouse?

**Comment by casanovalx** [comment]
I did use the official software, and it works flawlessly. Can even make a Windows 7 VM and test it, - it's a 2 minute job

**Comment by so1der** [comment]
If the manufacturer's software works, then I'm really out of guesses...

From what I can see, everything should be working. Though, I'm not entirely sure about the system since I haven't dealt with openSUSE at all. But at least from the packets, it looks like the CLI was able to correctly form and send the packet. Why the mouse doesn’t change the mode is a mystery to me

**Comment by casanovalx** [comment]
Just checked the official software via VirtualBox (compared to VMWare, it can transfer the keyboard/mouse signals even if they're in use), and everything works... That's truly weird...

**Comment by so1der** [comment]
Yeah, it’s really strange, because I wrote this script "mimicking" the original software – I intercepted a lot of packets, analyzed them, and made the script behave almost the same way as the original program.

Considering that it works for me and there are other users who’ve confirmed the script is working, maybe this issue is indeed system-related. Or they changed something, and updated their software.

Btw, if you have another Linux distribution in VirtualBox, it might be worth trying there to rule out any system interference. I confirmed it working on Ubuntu, Arch, and POP_OS (Ubuntu-based).

**Comment by casanovalx** [comment]
> Yeah, it’s really strange, because I wrote this script "mimicking" the original software – I intercepted a lot of packets, analyzed them, and made the script behave almost the same way as the original program.
> 
> Considering that it works for me and there are other users who’ve confirmed the script is working, maybe this issue is indeed system-related. Or they changed something, and updated their software.
> 
> Btw, if you have another Linux distribution in VirtualBox, it might be worth trying there to rule out any system interference. I confirmed it working on Ubuntu, Arch, and POP_OS (Ubuntu-based).

Sorry for absence. Just checked on Lubuntu. Same crap. Yet the mode switch works, after all (because I set a lil, config on Win7 and on second mode I have the default config, it simply switches the lighting momentarily, without the red-blue mode switch indicator), yet writing configs still doesn't work, which's strange...

**Comment by so1der** [comment]
Eeh, this is really strange, considering that the mouse does react to mode changes.

Maybe the issue is actually mouse-related after all. But it's still really weird that the original software works without any problems.

I’m honestly out of guesses at this point, sorry that I couldn’t help :(

**Comment by casanovalx** [comment]
> Eeh, this is really strange, considering that the mouse does react to mode changes.
> 
> Maybe the issue is actually mouse-related after all. But it's still really weird that the original software works without any problems.
> 
> I’m honestly out of guesses at this point, sorry that I couldn’t help :(

No problem. Yet maybe, just maybe, there may be different signals for different revisions (?). I just bought it a year ago in Strela for 65 BYN, and had no issues (except for settings) whatsoever...

**Comment by so1der** [comment]
Yeah, maybe. There were a couple of bytes in the packets that I couldn’t figure out, so it’s possible that the original software uses them to determine the revision or something like that and then modifies the packets accordingly.

Although my script is designed in a way that it reads the mouse settings and only changes the parts I understood, meaning the unknown bytes remain unchanged, but it’s possible that a newer revision has a completely different communication protocol.

I bought my mouse about two years ago. By the way, I took it apart, and there was a date and some numbers on the PCB—maybe that indicates the revision.

But please, don’t take your mouse apart just to check that! :D Taking it apart is such a pain in the ass because the screws are hidden under the mouse's Teflon feet.

![Image](https://github.com/user-attachments/assets/0c40f83c-0413-4a45-bf18-278d53160edf)
